### Importing the necessary package

In [1]:
import pandas as pd
import requests

In [7]:
# reading the dataset
df = pd.read_csv('article.csv').iloc[:,1:]
df

,Title,URL,Section,Original Text
0,The AI Revolution: The Road to Superintelligence,https://waitbutwhy.com/2015/01/artificial-inte...,Introduction,We are on the edge of change comparable to the...
1,The AI Revolution: The Road to Superintelligence,https://waitbutwhy.com/2015/01/artificial-inte...,The Far Future—Coming Soon,Imagine taking a time machine back to 1750—a t...
2,The AI Revolution: The Road to Superintelligence,https://waitbutwhy.com/2015/01/artificial-inte...,The Road to Superintelligence,"What Is AI?If you’re like me, you used to thin..."
3,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Introduction,One of the most common types of advice we give...
4,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Recruit,The most common unscalable thing founders have...
5,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Fragile,Airbnb now seems like an unstoppable juggernau...
6,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Delight,You should take extraordinary measures not jus...
7,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Experience,I was trying to think of a phrase to convey ho...
8,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Fire,Sometimes the right unscalable trick is to foc...
9,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Meraki,ForHardware startups face an obstacle that sof...
10,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Consult,Sometimes we advise founders of B2B startups t...
11,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Manual,There's a more extreme variant where you don't...
12,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Big,I should mention one sort of initial tactic th...
13,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Vector,The need to do something unscalably laborious ...

In [ ]:
import os
from dotenv import load_dotenv

load_dotenv()

#using the huggingface api inference to summarize the sections using sshleifer/distilbart-cnn-6-6

API_URL = "https://api-inference.huggingface.co/models/sshleifer/distilbart-cnn-6-6"
API_TOKEN = os.getenv('HUGGINGFACE_API_KEY')
headers = {"Authorization": f"Bearer {API_TOKEN}"}

# function for POST Reequest and GET the response
def query(payload):
    response = requests.post(API_URL, headers=headers, json=payload)
    return response.json()

# get the summary of each section in the dataframe['Original Text']
output = query({
    "inputs": df['Original Text'].to_list(),
})

In [17]:
# create a list of response summaries
summary = []

for i in range(len(output)):
    summary.append(output[i]['summary_text'])

print(len(summary))
print(summary)

14
[" We are on the edge of change comparable to the rise of human life on Earth . It seems like a pretty intense place to be standing, but then you have to remember something about what it's like to stand on a time graph: you can’t see what's to your right .", ' A time machine would take a man from around the year 1500, bring him to 1750, and show him everything . It would be far less of an insane experience for him, because while 1500 and 1750 were very different, they were much less different than 1750 to 2015 . In order for the 1750 guy to have', 'There are three reasons a lot of people are confused about the term AI . John McCarthy, who coined the term ‘Artificial Intelligence’ in 1956, complained that “as soon as it works, no one calls it AI anymore’s AI.’', " A lot of would-be founders believe that startups either take off or don't . A good metaphor would be the cranks that car engines had before they got electric starters . Once the engine was going, it would keep going, but there was aseparate and laborious process to get it going .", "Stripe is one of the most successful startups we've funded, and the problem they solved was an urgent one . But in fact they're famous within YC for aggressive early user acquisition . There are two reasons founders resist going out and recruiting users individually . The mistake they make is tounderestimate the power of compound", " Airbnb now seems like an unstoppable juggernaut, but early on it was so fragile that about 30 days of going out and engaging in users made the difference between success and failure . It's harmless if reporters and know-it-alls dismiss your startup; they'll change their minds when they see growth .", ' Wufoo sent each new user a hand-written thank you note after you bought a laptop . Why do we have to teach startups this? Why is it counterintuitive for founders? One reason is that a lot of startup founders are trained as engineers, and customer service is not part of the training of engineers .', ' Steve Jobs used "insanely" as a synonym for "very" when he started using that phrase . He meant it more literally — that one should focus on quality of execution to a degree that in everyday life would be pathological . For most successful startups it\'s a necessary part of the feedback loop that makes the product good.', " The strategy works just as well if you don't do it unconsciously. Most startups that use the contained fire strategy do it subconsciously . The biggest danger of not being consciously aware of this pattern is for those who naively discard part of it . B2B startups now have an instant market of hundreds of other startups ready at hand", " For hardware startups face an obstacle that software startups don't have to raise money to manufacture their product . The arrival of crowdfunding has helped a lot, but even so I'd advise startups to pull a Meraki initially if they can . The Pebbles like paying excessive attention to early customers, fabricating things yourself turns out to be valuable", "Consulting is the canonical example of work that doesn't scale, but it's safe to do it so long as you're not being paid to . The initialuser serves as the form for your mold; keep tweaking till you fit your needs perfectly . Another consulting-like technique for recruiting initially lukewarmusers is to", "When you only have a small number of users, you can sometimes get away with doing by hand things that you plan to automate later . This lets you launch faster, and when you do it yourself, you'll know exactly what to build because you'll have muscle memory from doing it yourself .", " The Big Launch is an initial tactic that usually doesn't work. It's a common mistake among inexperienced founders to believe that a partnership with a big company will be their big break . It's not enough just to do something extraordinary initially, says the author . But getting users will always be a gradual process, he says .", " The need to do something unscalably laborious to get started is so universal that it might be a good idea to stop thinking of start-up ideas as scalars . Instead we should try thinking of them pairs of what you're going to build, plus the unscalable thing(s) you're Going to do"]

In [19]:
# add summary to the original dataframe

df['Summary'] = summary
df

,Title,URL,Section,Original Text,Summary
0,The AI Revolution: The Road to Superintelligence,https://waitbutwhy.com/2015/01/artificial-inte...,Introduction,We are on the edge of change comparable to the...,We are on the edge of change comparable to th...
1,The AI Revolution: The Road to Superintelligence,https://waitbutwhy.com/2015/01/artificial-inte...,The Far Future—Coming Soon,Imagine taking a time machine back to 1750—a t...,A time machine would take a man from around t...
2,The AI Revolution: The Road to Superintelligence,https://waitbutwhy.com/2015/01/artificial-inte...,The Road to Superintelligence,"What Is AI?If you’re like me, you used to thin...",There are three reasons a lot of people are co...
3,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Introduction,One of the most common types of advice we give...,A lot of would-be founders believe that start...
4,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Recruit,The most common unscalable thing founders have...,Stripe is one of the most successful startups ...
5,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Fragile,Airbnb now seems like an unstoppable juggernau...,Airbnb now seems like an unstoppable juggerna...
6,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Delight,You should take extraordinary measures not jus...,Wufoo sent each new user a hand-written thank...
7,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Experience,I was trying to think of a phrase to convey ho...,"Steve Jobs used ""insanely"" as a synonym for ""..."
8,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Fire,Sometimes the right unscalable trick is to foc...,The strategy works just as well if you don't ...
9,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Meraki,ForHardware startups face an obstacle that sof...,For hardware startups face an obstacle that s...
10,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Consult,Sometimes we advise founders of B2B startups t...,Consulting is the canonical example of work th...
11,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Manual,There's a more extreme variant where you don't...,"When you only have a small number of users, yo..."
12,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Big,I should mention one sort of initial tactic th...,The Big Launch is an initial tactic that usua...
13,Do Things that Don't Scale,http://www.paulgraham.com/ds.html,Vector,The need to do something unscalably laborious ...,The need to do something unscalably laborious...

In [21]:
# save the dataframe as csv and json file

df.to_csv('article_summaries.csv')
df.to_json('article_summaries.json')